version: '3.1'

services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      NODE_ENV: development

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      